export const projects = [
    { 
        title: "Cimba - City Management Tool",
        thumbnail: require("./images/cimba_thumb.jpg"),
        banner: require("./images/cimba_banner.jpg"),
        genre: "Product & System Design",
        client:"Nutanix",
        brief: "The goal was to imagine the working of a social rating system & design an interface that helps the Mayor to monitor the city’s state, identify issues & suggest solutions and rate the citizens based on that system",
        duration: "10 days (March '19)",
        roles: "System Analysis\nPlanning & Ideation\nIntegration\nWorkflows\nUser Research\nJourney Mapping\nWireframes\nScenarios\n",
        medium: "https://medium.com/usabilitygeek/240-hours-of-ux-nutanix-design-competition-f3a98123ccdb",
    },
    {    
        title: "Odin - The Marketplace Cerebrum",
        thumbnail: require("./images/odin_thumb.jpg"),
        banner: require("./images/odin_banner.jpg"),
        genre: "product design",
        client:"Wheelseye",
        brief: "Odin is a supply-demand management portal for a logistics based startup - Wheelseye. It is an internal product used by the employees from various verticals in a collaborative fashion to handle the various operational and financial aspects of the company",
        duration: "2 months (Dec'19 - Jan'20)",
        roles: "User Research\nJourney Mapping\nInformation Architecture\nWorklows\nWireframing\n",
        medium: "https://medium.com/design-studio-iit-roorkee/designing-for-the-employees-winter-2019-internship-at-wheelseye-8b9c15705670",
    },
    { 
        title: "Design Challenge: IELTS App UI",
        thumbnail: require("./images/ielts_thumb.jpg"),
        banner: require("./images/ielts_banner.jpg"),
        genre: "UI/UX design",
        client:"Design Challenge",
        brief: "The current layouts are not the best visual presentation of the flow. This can be completely redesigned as far as the process, logic, and fields don’t change.Good usability.Appropriate aesthetics for the demographic, tone, mobile/touch paradigms, etc.insight into your process, including any sketches, brainstorms, notes, wireframes, and assumptions on the product.offer a design direction and final design.Alignment with current consumer trends ",
        duration: "5 days (17 Sep 20 - 23 Sep 20)",
        roles: "User Research\nCompetitive Analysis\nUser Flows\nInformation Structuring\nWireframing\nPrototyping\n",
        medium: "https://subsequent-whistle-7a4.notion.site/Design-Challenge-IELTS-App-UI-7b899f355987413fb30c785e9dd3e340",
        // behance: "https://www.behance.net/gallery/81553689/Kookerr-A-hands-free-cooking-app-concept-UIUX",
    },
]